### ISSUE TITLE
Add support for multiple items

### ISSUE THREAD

**Issue by chih98** [joogps/SlideOverCard#1]
Add support so that the view can be called with multiple items such as
```Swift
        .sheet(item: $activeSheet) { item in
            switch item {
            case .photoPicker:
                ImagePicker(selectedImage: $imageBuffer, sourceType: .photoLibrary)
            case ........
```

**Comment by joogps** [comment]
@chih98 I just addressed this on ddf43e9fbed9f8d21ceb5a375f024767fca30843
there's now an extra method that accepts a `Binding` of an optional, `Identifiable`-conforming, object as a parameter
it _should_ work just like the `.sheet()` call haha

**Comment by joogps** [comment]
I don't think it will switch like sheets though... tbh I don't even know how I would even do that

**Comment by joogps** [comment]
added with [1.1.0](https://github.com/joogps/SlideOverCard/releases/tag/1.1.0)!
