### ISSUE TITLE
Documentation need to be updated for Xcode 13?

### ISSUE THREAD

**Issue by adams-family** [joogps/SlideOverCard#11]
This might be actually my limited knowledge on how to use Swift Packages but the documentation says that I'm supposed to go to ***File > Swift Package Manager***.

I don't see such menu item so I was trying to do it another way but still can't make it work:

![2022-01-06 17 34 06](https://user-images.githubusercontent.com/19559733/148417207-d8197e69-c935-4631-a343-22d1892b9435.gif)

Any hints on how to link this package?

**Comment by joogps** [comment]
hi @adams-family! you're right, adding a swift package changed along the way
what you can do for now is paste the entire repository link in the search bar and it should work :)

I'm working on a huge update to this component for now, but I'll make sure to update the README soon

**Comment by joogps** [comment]
fixed with 791197c26a0fea83fcf31b1e9fb9a324db7a4b0b :D

**Comment by joogps** [comment]
also, fun side note: if you link your GitHub with Xcode, you get a nice list of starred repos in the SPM modal sidebar
<img width="263" alt="image" src="https://user-images.githubusercontent.com/41346220/148609942-6db4547b-84c8-4e08-b5ad-fe03903844d6.png">
