### ISSUE TITLE
Close on Tap Outside

### ISSUE THREAD

**Issue by Mcrich23** [joogps/SlideOverCard#13]
Is there a way you can make it, so a tap outside of the card dismisses it. Thanks!

**Comment by corbin-r** [comment]
Seems to me like this could be implemented into here, as well as further down in the code:
https://github.com/joogps/SlideOverCard/blob/791197c26a0fea83fcf31b1e9fb9a324db7a4b0b/Sources/SlideOverCard/SlideOverCard.swift#L24
Using `struct TouchGesture` from SwiftUI, detect when a tap gesture that's outside the card's view and close it from there. Looking into `SlideOverCard.swift`'s logic, it appears that there's logic already in place to detect dragging so shouldn't be too hard! 

I can start work on this @joogps if you're okay with that 🙂

**Comment by joogps** [comment]
@Mcrich23 @corbin-r thank you for your support!
