### ISSUE TITLE
How to manually add to a project?

### ISSUE THREAD

**Issue by Aiyush-G** [joogps/SlideOverCard#16]
Hi, 

I would like to use this in Swift Playgrounds? I was thinking that the best way to do this was copy and paste the source files, but I'm not sure which ones to copy and to where?

Thanks

**Comment by joogps** [comment]
Hi there, Aiyush! If you're working on a Playgrounds App, you can add SlideOverCard as a dependency IIRC. If not, you can just copy all of the files over to your project. Ideally, you should keep them in a separate folder if possible!
