### ISSUE TITLE
SOCManager present animation speed

### ISSUE THREAD

**Issue by wambambizzle** [joogps/SlideOverCard#17]
Version: `SlideOverCard` 2.0.0, Xcode 13.3
Issue: Unnaturally fast animation when displaying a card using `SOCManager.present` vs ` .slideOverCard(isPresented`.

I would expect both versions to display the card at the same animation speed. The `SOCManager` presents the card so quickly that it feels off. 

Potential Quick Fix:
Give the `SOCManager` the same animation speed as the `slideOverCard`

Potential Enhancement:
Add and option to change the speeds between slow, medium, fast, and or passing in custom animation speeds

Code snippets:

```
Button {
    showLogIn = true

    SOCManager.present(isPresented: $showLogIn, onDismiss: {
       // code
    }, options: [.disableDrag, .disableDragToDismiss, .hideExitButton]) {
      SomeView(isPresented: $showLogIn)
    }
  }
}
```

```
.slideOverCard(isPresented: $showView, options: [.disableDrag, .disableDragToDismiss, .hideExitButton]) {
  SomeView(isPresented: $showSummary)
}
```

Thank you for your time.

**Comment by antonioreyna** [comment]
same problem here

**Comment by Bartozo** [comment]
I have the same problem with `SOCManager.present`, which is presented too fast. Are there plans to fix this issue?

**Environment:**
Xcode version: 15.0.1
SlideOverCard version: 2.1.0
