### ISSUE TITLE
5 issues , when install using package manager

### ISSUE THREAD

**Issue by freddokresna** [joogps/SlideOverCard#23]
<img width="256" alt="Screen Shot 2022-09-06 at 09 46 59" src="https://user-images.githubusercontent.com/753514/188536584-646faa90-3539-44bc-9c7b-d0118a015661.png">

hello,
i'm countered with 5 errors, one of the error was Generic parameter 'Style' could not be inferred

anyone can help?

**Comment by freddokresna** [comment]
the version was 2.1.0 and 2.0.0

but when using 1.2.6 the error did not occured.

**Comment by Elshir** [comment]
We've noticed this error too, trying to fix it now, will be done on next release!

**Comment by jcleggss** [comment]
+1 to 2.1.0 in Xcode 13.4 building on iPhone 13.0 iOS 15.0

**Comment by jrclegg2** [comment]
+1 to 2.1.0 in Xcode 13.4 building on iPhone 13.0 iOS 15.0
