### ISSUE TITLE
Can I use multiple slideOverCard modifiers across the project?

### ISSUE THREAD

**Issue by chichkanov** [joogps/SlideOverCard#28]
1. Right now only the first modifier works for me. When I close the SlideOverCard I can't open it again
2. Is it possible to overlay SlideOverCard on top of each other? For example I open SlideOverCard A from the screen, but A also contains SlideOverCard B which should be opened on top

**Comment by joogps** [comment]
Hi @chichkanov! Thank you for pointing this out. You should technically be able to work with multiple SlideOverCards with no big issues. I'll take a look at what could be going on.

**Comment by chichkanov** [comment]
Thanks @joogps 

I decided to split this issue into https://github.com/joogps/SlideOverCard/issues/31 and https://github.com/joogps/SlideOverCard/issues/30.
Also was experiencing something similar to https://github.com/joogps/SlideOverCard/issues/29

Closing this in favor of them
