### ISSUE TITLE
Change slide over position and possible options

### ISSUE THREAD

**Issue by chellem** [joogps/SlideOverCard#9]
Hi @joogps,

I wanted to know how to make the slide to open from different position instead from the default bottom position.

Sorry if I have missed it from the `SOCManager`, I didn't get it very well.

Regards,

**Comment by joogps** [comment]
Sorry for the late response! I will be refactoring the codebase and adding that option. :D

**Comment by chellem** [comment]
Thank for the sarcasm.

unstar and remove from my projects ;)
